{"name": "Test case ID: TS53", "status": "broken", "statusDetails": {"message": "AttributeError: 'str' object has no attribute 'to_dict'", "trace": "test_setup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"644f9b9d26b2ef7cece4a735da90dde3\")>\n\n    @allure.description(\"navigate to contact us\")\n    @allure.severity(severity_level=\"LOW\")\n    @allure.title(\"Test case ID: TS53\")\n    def test_11_contact_us(test_setup):\n        try:\n            driver = test_setup\n            fo = Footer(driver)\n            hp = HomePage(driver)\n            hp.click_save_button()\n            fo.contact_us()\n>           assert driver.current_url == 'https://qa.trado.co.il/contact'\nE           AssertionError: assert 'https://qa.t...product/04991' == 'https://qa.t...co.il/contact'\nE             - https://qa.trado.co.il/contact\nE             ?                        ^ ^^^\nE             + https://qa.trado.co.il/product/04991\nE             ?                        ^^ ^^  ++++++\n\ntests\\test_footer.py:194: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\ntest_setup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"644f9b9d26b2ef7cece4a735da90dde3\")>\n\n    @allure.description(\"navigate to contact us\")\n    @allure.severity(severity_level=\"LOW\")\n    @allure.title(\"Test case ID: TS53\")\n    def test_11_contact_us(test_setup):\n        try:\n            driver = test_setup\n            fo = Footer(driver)\n            hp = HomePage(driver)\n            hp.click_save_button()\n            fo.contact_us()\n            assert driver.current_url == 'https://qa.trado.co.il/contact'\n        except Exception as e:\n            print(e)\n>           driver.print_page(\"test_TS53_error.png\")\n\ntests\\test_footer.py:197: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"644f9b9d26b2ef7cece4a735da90dde3\")>, print_options = 'test_TS53_error.png'\n\n    def print_page(self, print_options: Optional[PrintOptions] = None) -> str:\n        \"\"\"Takes PDF of the current page.\n    \n        The driver makes a best effort to return a PDF based on the\n        provided parameters.\n        \"\"\"\n        options = {}\n        if print_options:\n>           options = print_options.to_dict()\nE           AttributeError: 'str' object has no attribute 'to_dict'\n\nvenv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:610: AttributeError"}, "description": "navigate to contact us", "attachments": [{"name": "stdout", "source": "3a643f45-ef9e-434f-8fa0-b5d5602bcf8e-attachment.txt", "type": "text/plain"}], "start": 1680424713824, "stop": 1680424714248, "uuid": "e142f3b3-6a8f-4e1a-895c-13f53557600e", "historyId": "3c09419d26ff21914659014af55a6e6c", "testCaseId": "aba59b5147821a7cd0499d7770950ff2", "fullName": "tests.test_footer#test_11_contact_us", "labels": [{"name": "severity", "value": "LOW"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_footer"}, {"name": "host", "value": "DESKTOP-9HU6DH7"}, {"name": "thread", "value": "34884-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_footer"}]}