{"name": "Test case ID: TS05", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "test_setup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"c57f04e17d974c8204b27028cb7b2d7a\")>\n\n    @allure.description(\"validate navigation to the commercal\")\n    @allure.severity(severity_level=\"NORMAL\")\n    @allure.title(\"Test case ID: TS05\")\n    def test_4_Navigate_to_Commercial_hand_with_phone_button(test_setup):\n        try:\n            driver = test_setup\n            hp = HomePage(driver)\n            lgn = Login(driver)\n            hp.click_save_button()\n            lgn.move_to_login()\n            lgn.login(\"0586691039\")\n            lgn.submit_login()\n            lgn.login_input_squares()\n            lgn.submit_secret_code()\n            hp.click_right_arrow()\n            hp.commercial_man_with_phone()\n            assert hp.assert_commercial_man_with_phone()\n        except Exception as e:\n            print(e)\n            driver.save_screenshot(\"test_TS05_error.png\")\n>           raise e\n\ntests\\test_homepage.py:70: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntests\\test_homepage.py:65: in test_4_Navigate_to_Commercial_hand_with_phone_button\n    hp.commercial_man_with_phone()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Src.pages.HomePage.HomePage object at 0x00000235569BF490>\n\n    def commercial_man_with_phone(self):\n        commercial_xpath = '//*[@id=\"root\"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div[1]/div/div/div/div/ul/li[3]/a'\n        element = self.driver.find_element(By.XPATH, commercial_xpath)\n        self.driver.execute_script(\"arguments[0].click();\", element)\n>       self.driver.switch_to.window(self.driver.window_handles[1])\nE       IndexError: list index out of range\n\nSrc\\pages\\HomePage.py:71: IndexError"}, "description": "validate navigation to the commercal", "attachments": [{"name": "stdout", "source": "88b8a61a-febf-41a1-b491-b4bd1b03c91d-attachment.txt", "type": "text/plain"}], "start": 1680419592182, "stop": 1680419595502, "uuid": "2cc6c846-326a-4468-bae5-db5e9564f32d", "historyId": "9d4b3479a08b05f68291f77b5bff98a6", "testCaseId": "b83cf6b71f7d398058ea8eeb4062bbe4", "fullName": "tests.test_homepage#test_4_Navigate_to_Commercial_hand_with_phone_button", "labels": [{"name": "severity", "value": "NORMAL"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_homepage"}, {"name": "host", "value": "DESKTOP-9HU6DH7"}, {"name": "thread", "value": "14412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_homepage"}]}